# Generated by Django 4.2.1 on 2023-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('department', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
