# Generated by Django 4.2.1 on 2023-05-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='departament',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
