# Generated by Django 4.2.1 on 2023-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='registration',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
