# Generated by Django 4.2.1 on 2023-05-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_departament_teacher_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='registration',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
