# Generated by Django 4.2.1 on 2023-05-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_period', models.IntegerField()),
                ('shift', models.CharField(choices=[('Manhã', 'Matutino'), ('Tarde', 'Vespertino'), ('Noite', 'Noturno')], max_length=10)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ClassCanceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled_date', models.DateField()),
                ('reason', models.TextField(blank=True, max_length=200, null=True)),
                ('is_avaible', models.BooleanField()),
            ],
            options={
                'db_table': 'class_canceled',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=20)),
                ('course_load', models.IntegerField()),
                ('byname', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=15)),
                ('workload_in_clock', models.IntegerField()),
                ('workload_in_class', models.IntegerField()),
                ('is_optional', models.BooleanField()),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='TeachTemporarily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('class_canceled_id', models.ForeignKey(db_column='class_canceled_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.classcanceled')),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.discipline')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
            ],
            options={
                'db_table': 'teach_temporarily',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='course.class')),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline')),
                ('teacher_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'teach',
            },
        ),
        migrations.CreateModel(
            name='SubstituteTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_canceled_id', models.ForeignKey(db_column='class_canceled_id', on_delete=django.db.models.deletion.CASCADE, to='course.classcanceled')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'substitute_teachers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weekday', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='course.class')),
                ('discipline_id', models.ForeignKey(db_column='discilpine_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.discipline')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='CourseDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.discipline')),
            ],
            options={
                'db_table': 'course_discipline',
            },
        ),
        migrations.AddField(
            model_name='classcanceled',
            name='schedule_id',
            field=models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.schedule'),
        ),
        migrations.AddField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.course'),
        ),
    ]
