# Generated by Django 4.2.1 on 2023-06-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_class_class_leader_class_class_leader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
