# Generated by Django 4.2.1 on 2023-06-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscipline',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
