# Generated by Django 4.2.1 on 2023-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'code', 'verbose_name_plural': 'codes'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
