# Generated by Django 4.2.1 on 2023-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0004_rename_teachtemporarily_temporaryclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcanceled',
            name='teachers_id',
            field=models.ManyToManyField(related_name='substitute_teachers', to='teacher.teacher'),
        ),
        migrations.DeleteModel(
            name='SubstituteTeachers',
        ),
    ]
