# Generated by Django 4.2.1 on 2023-05-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0005_classcanceled_teachers_id_delete_substituteteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcanceled',
            name='teachers_id',
            field=models.ManyToManyField(blank=True, related_name='substitute_teachers', to='teacher.teacher'),
        ),
    ]
