# Generated by Django 4.2.1 on 2023-07-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_email'),
        ('course', '0006_remove_classcanceled_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcanceled',
            name='teacher_id',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
        ),
    ]
