# Generated by Django 4.2.1 on 2023-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0006_alter_classcanceled_teachers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcanceled',
            name='teachers_id',
            field=models.ManyToManyField(blank=True, db_column='substitute_teachers', null=True, to='teacher.teacher'),
        ),
    ]
