# Generated by Django 4.2.1 on 2023-05-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_registration'),
        ('course', '0006_alter_discipline_options_class_class_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='classcanceled',
            name='schedule_id',
            field=models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, to='course.schedule'),
        ),
        migrations.AlterField(
            model_name='coursediscipline',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursediscipline',
            name='discipline_id',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='discipline_id',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline'),
        ),
        migrations.AlterField(
            model_name='teachtemporarily',
            name='class_canceled_id',
            field=models.ForeignKey(db_column='class_canceled_id', on_delete=django.db.models.deletion.CASCADE, to='course.classcanceled'),
        ),
        migrations.AlterField(
            model_name='teachtemporarily',
            name='discipline_id',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline'),
        ),
        migrations.AlterField(
            model_name='teachtemporarily',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
