# Generated by Django 4.2.1 on 2023-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_classcanceled_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcanceled',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pending'), ('Recusado', 'Refused'), ('Aceito', 'Accepted')], default='Pendente', max_length=10),
        ),
    ]
