# Generated by Django 4.2.1 on 2023-05-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_class_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='courses',
            field=models.ManyToManyField(related_name='courses_disciplines', through='course.CourseDiscipline', to='course.course'),
        ),
    ]
