# Generated by Django 4.2.1 on 2023-05-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_teach_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classcanceled',
            old_name='is_avaible',
            new_name='is_available',
        ),
    ]
