# Generated by Django 4.2.1 on 2023-07-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_email'),
        ('course', '0008_classcanceled_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classcanceled',
            old_name='status',
            new_name='replace_class_status',
        ),
        migrations.RemoveField(
            model_name='classcanceled',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='classcanceled',
            name='canceled_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classcanceled',
            name='teacher_to_replace',
            field=models.ForeignKey(blank=True, db_column='teacher_to_replace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
        ),
    ]
