# Generated by Django 4.2.1 on 2023-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0008_remove_classcanceled_teachers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcanceled',
            name='teacher_ids',
            field=models.ManyToManyField(blank=True, db_column='teacher_ids', db_table='substitute_teachers', to='teacher.teacher'),
        ),
    ]
