# Generated by Django 4.2.1 on 2023-05-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_discipline_courses'),
        ('course', '0009_rename_is_avaible_classcanceled_is_available'),
    ]

    operations = [
    ]
