# Generated by Django 4.2.1 on 2023-05-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_classcanceled_teacher_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcanceled',
            name='quantity_available',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
