# Generated by Django 4.2.1 on 2023-07-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_status_classcanceled_replace_class_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryclass',
            name='quantity',
        ),
    ]
