# Generated by Django 4.2.1 on 2023-05-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='course.class')),
                ('disciplines', models.ManyToManyField(to='course.discipline')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=200, null=True)),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'student_alert',
            },
        ),
    ]
