# Generated by Django 4.2.1 on 2023-05-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
