# Generated by Django 4.2.1 on 2023-07-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_email'),
        ('student', '0003_alter_studentalert_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentalert',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
