# Generated by Django 4.2.1 on 2023-05-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_class_course_id_and_more'),
        ('student', '0003_alter_student_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentalert',
            name='discipline_id',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='course.discipline'),
        ),
    ]
