# Generated by Django 4.2.1 on 2023-05-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_class_course_id_and_more'),
        ('student', '0004_alter_studentalert_discipline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
        migrations.AlterField(
            model_name='studentalert',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
