# Generated by Django 4.2.1 on 2023-07-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentalert_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
